# Makefile for KGEN-generated kernel
#
FC := ifort
SRC := ./kernel_inatm.F90
EXE := ${SRC:.F90=.exe}
#FFLAGS := -O3 -mmic -qopt-report=5 -fp-model fast
#FFLAGS := -fp-model precise
#FLAGS := -xAVX ${FFLAGS}
FLAGS := -O3 -no-prec-div -fp-model fast=2 -xHost

run: build
	${EXE}

build: ${SRC} clean
	${FC} ${FLAGS} -o ${EXE} ${SRC}

clean:
	rm -f *.exe
