# Makefile for KGEN-generated kernel
#
FC := pgfortran
SRC := ./kernel_cldprmc.F90
EXE := ${SRC:.F90=.exe}
#FFLAGS := -O3 -mmic -qopt-report=5 -fp-model fast
#FFLAGS := -fp-model precise
FLAGS := -fast -Mipa=fast,inline

run: build
	${EXE}

build: ${SRC} clean
	${FC} ${FLAGS} -o ${EXE} ${SRC}

clean:
	rm -f *.exe *.oo
