FC := ifort
SRC := ./kernel_binterp.F90
EXE := ${SRC:.F90=.exe}
#FFLAGS :=  -O3 -xAVX -ftz  -ip  -no-fp-port -fp-model fast -no-prec-div -no-prec-sqrt -override-limits -align array64byte -DCPRINTEL -mkl
FFLAGS := -O3 -no-prec-div -fp-model fast=2 -xHost
FLAGS := ${FFLAGS}

run: build
	${EXE}

build: ${SRC} clean
	${FC} ${FLAGS} -o ${EXE} ${SRC}

clean:
	rm -f *.exe *.mod
