# Makefile for KGEN-generated kernel
#
FC := pgfortran
SRC := ./kernel_laplace_sphere_wk.F90
EXE := ${SRC:.F90=.exe}
#FFLAGS := -O3 -mmic -qopt-report=5 -fp-model fast
#FFLAGS := -O3 -xAVX -qopt-report=5 -fp-model fast
#FFLAGS := -O3 -qopt-report=5 -fp-model fast
FLAGS := -fast -Mipa=fast,inline

run: build 
	${EXE}

build: ${SRC} clean
	${FC} ${FLAGS} -o ${EXE} ${SRC}

clean:
	rm -f *.exe
